ALTER TABLE dbo.Product
ADD CONSTRAINT PK_Product PRIMARY KEY CLUSTERED (ProductID);

ALTER TABLE dbo.Customer
ADD CONSTRAINT PK_Customer PRIMARY KEY CLUSTERED (CustomerID);

ALTER TABLE dbo.[Order]
ADD CONSTRAINT PK_Order PRIMARY KEY CLUSTERED (OrderID);

ALTER TABLE dbo.Employee
ADD CONSTRAINT PK_Employee PRIMARY KEY CLUSTERED (EmployeeID);

ALTER TABLE dbo.Shipper
ADD CONSTRAINT PK_Shipper PRIMARY KEY CLUSTERED (ShipperID);

ALTER TABLE dbo.ProductCategory
ADD CONSTRAINT PK_ProductCategory PRIMARY KEY CLUSTERED (CategoryID);

ALTER TABLE dbo.OrderDetail
ADD CONSTRAINT PK_OrderDetail PRIMARY KEY CLUSTERED (OrderID, ProductID);

